### ISSUE TITLE
Missing documentation files in v0.16

### ISSUE THREAD

**Issue by orlitzky** [inversepath/tenshi#8]
Oh hey, long time =)

The Makefile still has,

```
DOCS = README.md INSTALL CREDITS LICENSE Changelog FAQ
```

but the INSTALL, CREDITS, and FAQ files aren't in the repo, so "make install" can't find them.

**Comment by abarisani** [comment]
Fixed in 4b8c68bdc4e8a470de0b849a353e56e827c3a2fd

I also updated the release accordingly: https://github.com/inversepath/tenshi/releases/tag/0.16

**Comment by orlitzky** [comment]
Thanks for the fourth or fifth time.
